http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "30000"
  apiAccount: "https://account-customerwebapihttpsystem-9c6e37.5sc6y6-1.usa-e2.cloudhub.io"
db:
  user: "admin"
  password: "password123"
sfdc1:
  username: "samuel.chapman-matos@empathetic-koala-bl9vmk.com"
  password: "Catedra251289*"
  token: "9sunZOQyzZjeBaEYjUaCoHZ6"
sfdc:
  username: "samuelchapmanmatos12@gmail.com"
  password: "Catedra251289"
  token: "ITlEFNIuB6DZ9ZMgt0qoyyD89"
sfdc2:
  username: "samuelchapmanmatos13@gmail.com"
  password: "Catedra251289"
  token: "XOue0OUYiuWrKvnWdlPd84Yl"
